<<<<<<< HEAD
name: Deploy Shopify Theme (Live)
=======
name: CI/CD Shopify Theme
>>>>>>> parent of f593c8e (Update deploy.yml)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    environment: shopify secrets
    name: Deploy to Shopify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

<<<<<<< HEAD
      - name: Push theme to Shopify (Live)
=======
      - name: Deploy to Shopify
>>>>>>> parent of f593c8e (Update deploy.yml)
        env:
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_ADMIN_API_TOKEN: ${{ secrets.SHOPIFY_ADMIN_API_TOKEN }}
        run: |
<<<<<<< HEAD
          shopify theme push --theme 179739263325
=======
          shopify theme push --store ${SHOPIFY_STORE_URL} --password ${SHOPIFY_ADMIN_API_TOKEN} --theme 179739263325 --allow-live
>>>>>>> parent of f593c8e (Update deploy.yml)
